---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
ms.openlocfilehash: 53f19619824f306b64e9826a475c28f311af5497
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/17/2020
ms.locfileid: "79465296"
---
# <a name="c28163"></a>C28163

> 警告 C28163: 関数を try/except ブロック内から呼び出さないでください

この警告は、関数が `try/except` ブロックで囲むことができない型の場合に、`try/except` ブロックで見つかったときに報告されます。 コード分析ツールによって、関数が `try/except` ブロック内にある、少なくとも1つのパスが見つかりました。
