---
description: '詳細情報: C28125'
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
ms.openlocfilehash: abbcc0a89dd2d57ce34ef9d00acb6e79354d6d94
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/11/2020
ms.locfileid: "97151594"
---
# <a name="c28125"></a>C28125

> 警告 C28125: 関数は try/except ブロック内から呼び出される必要があります

ドライバーは、 [ProbeForRead](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread)、 [ProbeForWrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite)、 [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages)などの try/except ブロック内から呼び出す必要がある関数を呼び出しています。

## <a name="example"></a>例

次のコード例では、この警告が生成されます。

```cpp
ProbeForRead(addr, len, 4);
```

次のコード例では、この警告は生成されません。

```cpp
__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
