---
description: '詳細情報: C28198'
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
ms.openlocfilehash: 368180985a9541e87c8a74ff912ff29c3b883e03
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/11/2020
ms.locfileid: "97168528"
---
# <a name="c28198"></a>C28198

> 警告 C28198: 例外によりメモリがリークしている可能性があります

この警告は、例外が発生した後に割り当てられたメモリが解放されていないことを示します。 パスの末尾にあるステートメントは、例外を発生させることができます。 後で解放するためにコピーを保存した可能性のある関数にメモリが渡されました。

この警告は、warning [C28197](../code-quality/c28197.md)とよく似ています。 ここでは、警告 [C28197](../code-quality/c28197.md) と共に使用することをお勧めする注釈も使用できます。

## <a name="example"></a>例

次のコード例では、この警告が生成されます。

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

次のコード例では、この警告は生成されません。

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
