---
description: '詳細情報: C28105'
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
ms.openlocfilehash: fe61ed04a362a9119a7c529aeb0413cc5d39190f
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/11/2020
ms.locfileid: "97318261"
---
# <a name="c28105"></a>C28105

> 警告 C28105: 例外によりリソースがリークしています

指定されたリソースは、例外が発生したときに解放されません。 パスで指定されたステートメントで例外が発生する可能性があります。 この警告は警告 [C28103](../code-quality/c28103.md)に似ていますが、この場合は例外が関係している点が異なります。

## <a name="example"></a>例

次のコード例では、この警告が生成されます。

```cpp
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

次のコード例では、この警告は生成されません。

```cpp
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```
