---
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
ms.openlocfilehash: 3fa859f7bcc80040b62b538d37fb53d6169ff904
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/17/2020
ms.locfileid: "79466268"
---
# <a name="c28125"></a>C28125

> 警告 C28125: 関数は try/except ブロック内から呼び出される必要があります

ドライバーは、 [ProbeForRead](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread)、 [ProbeForWrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite)、 [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages)などの try/except ブロック内から呼び出す必要がある関数を呼び出しています。

## <a name="example"></a>例

次のコード例では、この警告が生成されます。

```cpp
ProbeForRead(addr, len, 4);
```

次のコード例では、この警告は生成されません。

```cpp
__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
